config/routes.rb
Napp::Application.routes.draw do
  

  resources :sites

  constraints subdomain: /^super$/ do
    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config
  end
  
  
  if Rails.env.development?
    constraints subdomain: /^script$/ do
      root to: 'scripts#index', as: :scripts
      get ':filename' => 'scripts#show', as: :script
      post ':filename' => 'scripts#run', as: :run_script
    end
  end
  
  constraints Proc.new { |r| puts '-------------------------'; puts r.env; true } do
    scope '/:page_name' do
      resource :site, :path => '/'
    end
  end
    
  
  match 'system/:action' => 'system'

  root to: 'sites#show', constraints: {subdomain: /.+/}
  
  match 'admin' => 'sites#show'
  constraints subdomain: /.+/ do
    
    resource :forum
    
    namespace :admin do
      resource :site
      resource :services
      resource :site_layout, only: [:edit, :show] do
        member do
          get 'preview'
        end
      end
    end
    
  end
  
  resource :layout, :controller => :layout 

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :name, :permalink, :site_id, :type
  
  belongs_to :site
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :name, :site, :slug
  
  has_one :site
end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :name, :owner_id, :owner, :subdomain, :layout, :layout_css, :disable_bootstrap
  
  belongs_to :owner, class_name: 'User'
  has_many :pages
  
  validates :name,
    presence: true,
    uniqueness: true
  validates :subdomain,
    presence: true,
    exclusion: {in: %w{www admin support service services}, message: "Subdomain %{value} is reserved"}
  
  validates :layout,
    format: {with: /\{\{content\}\}/, message: "Layout must contain {{content}} to specify where content appears." },
    allow_nil: true
    
  validates :layout,
    format: {with: /\{\{head\}\}/, message: "Layout must contain {{head}} at the top of the <head>." },
    allow_nil: true
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :company, :phone, :street, :city, :state, :zip
  
  belongs_to :site
end

app/models/wiki.rb
class Wiki < Service
  
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < ApplicationController
  
  before_filter :load_site
  layout 'admin'

end

app/controllers/admin/site_layouts_controller.rb
class Admin::SiteLayoutsController < ApplicationController
  before_filter :load_site
  layout 'admin'
end

app/controllers/admin/sites_controller.rb
class Admin::SitesController < ApplicationController
  
  before_filter :load_site
  layout 'site'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery

  def load_site
    @site = Site.find_by_subdomain!(request.subdomain)
  end
  
end

app/controllers/layout_controller.rb
class LayoutController < ApplicationController
  
  before_filter :load_site
  
  layout 'site'
  
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  
  before_filter :init_filename, only: [:show, :run]
  
  def init_filename
    @filename = sanitize_filename(params[:filename])
    @path = File.join('./app/scripts/', "#{@filename}.rb") 
  end
  
  def filename
    
  end
  
  def sanitize_filename(filename)
    name = filename.strip
    # NOTE: File.basename doesn't work right with Windows paths on Unix
    # get only the filename, not the whole path
    name.gsub!(/^.*(\\|\/)/, '')
   
    # Strip out the non-ascii character
    name.gsub!(/[^0-9A-Za-z.\-]/, '_')
    name
  end  
  
  def index
    @files = Dir.glob('./app/scripts/*.rb').map do |file|
      file.split('/').last.split('.').first
    end
  end
  
  def show
    # throw @filename
    # throw filename
    @content = File.read(@path)
  end
  
  def run
    begin
      load @path
    rescue => e
      @error = e
    end
    @content = File.read(@path)
    render :show
  end
  
end

app/controllers/sites_controller.rb
class SitesController < InheritedResources::Base
  
  before_filter :load_site
  
  layout 'site'
  
  def show
  end
  
end

app/controllers/system_controller.rb
class SystemController < ApplicationController
  
  def run
    # require 'populate'
    # Populate.users
    render :json => User.find(:all).sample
  end
  
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/admin/site/layout_helper.rb
module Admin::Site::LayoutHelper
end

app/helpers/admin/site_helper.rb
module Admin::SiteHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/system_helper.rb
module SystemHelper
end

app/views/admin/services/show.html.slim
css:
  .sidebar .btn-service {
    margin-bottom: 3px;
  }
  .sidebar .btn {
    width: 100%;
    text-align: left;
  }
  table.table td {
    vertical-align: middle;
  }
  table.table input {
    margin: 0px;
  }

link rel="stylesheet" href="/slickswitch/css/slickswitch.css" type="text/css"
script src="/slickswitch/js/jquery.slickswitch.js"
javascript:
  $(window).ready(function () {
    $('.switch').slickswitch();
  });

.row
  .span12
    h1 Services
.row
  .span9
    
    table.table.table-bordered
      tr
        th Service
        th Link to this URL
        th Enabled
      tr
        td Documentation
        td
          input type="text" value="http://site-1.lvh.me:3001/docs"
        td
          input type="checkbox" class="switch icons" checked="true"


    a href="" Switch to advanced view    
    /a.btn.btn-primary href="" Add a Service
  .span3.sidebar
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> Docs
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> Knowledge Base
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> FAQ
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> Feedback
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> Forum
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> Tickets
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> Issues
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> Suggestions
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> Notify Me
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> Mailing List
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> Blog
    div.btn-service
      a.btn <i class="icon-plus-sign"></i> Roadmap        

      
      

app/views/admin/sites/_form.html.slim
= form_for @site do |f|
  - if @site.errors.any?
    #error_explanation
      h2 = "#{pluralize(@site.errors.count, "error")} prohibited this site from being saved:"
      ul
        - @site.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :subdomain
    = f.text_field :subdomain
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :owner_id
    = f.number_field :owner_id
  .actions = f.submit 'Save'

app/views/admin/sites/edit.html.slim
h1 Editing site

== render 'form'

= link_to 'Show', @site
'|
= link_to 'Back', sites_path

app/views/admin/sites/new.html.slim
h1 New site

== render 'form'

= link_to 'Back', sites_path

app/views/admin/sites/show.html.slim
p#notice = notice

h1
  = @site.name
  

app/views/layout/edit.html.slim
h1 Editing Theme

= simple_form_for @site do |f|

  /
    - if @site.errors.any?
      #error_explanation
        h2 = "#{pluralize(@site.errors.count, "error")} prohibited this layout from being saved:"
        ul
          - @site.errors.full_messages.each do |message|
            li = message

  ==f.input :layout, as: :text, label: 'HTML for Layout'
  ==f.input :layout_css, as: :text, label: 'CSS for Layout'
  
  .field
    input type="checkbox"
    label for="" Disable built-in Bootstrap
  
  .actions = f.submit 'Save'

/ CodeMirror Stuff
script src="/codemirror/lib/codemirror.js"
link rel="stylesheet" href="/codemirror/lib/codemirror.css"
link rel="stylesheet" href="/codemirror/theme/twilight.css"
script src="/codemirror/mode/css/css.js"
script src="/codemirror/mode/xml/xml.js"
script src="/codemirror/mode/javascript/javascript.js"
script src="/codemirror/mode/css/css.js"
script src="/codemirror/mode/htmlmixed/htmlmixed.js"
javascript:
  CodeMirror.fromTextArea(document.getElementById('site_layout'), {
    theme: 'twilight',
    mode: 'htmlmixed',
    tabSize: 2,
    indentWithTabs: false,
    lineNumbers: true
  });
  CodeMirror.fromTextArea(document.getElementById('site_layout_css'), {
    theme: 'twilight',
    mode: 'css',
    lineNumbers: true
  });

= link_to 'Show', @site
'|
= link_to 'Back', sites_path

app/views/layouts/admin.html.slim
doctype html
html
  title Napp
  == stylesheet_link_tag    "admin", :media => "all"
  == javascript_include_tag "application"
  == csrf_meta_tags
body
  .container
    .row
      .span12
        .navbar
          .navbar-inner
            ul.nav
              li
                a href="Start" Start
              li
                a href="#{admin_services_path}" Services
              li
                a href="#{edit_admin_site_layout_path}" Theme
              li
                a href="Domain" Domain
              li
                a href="Users" Users
  .container
    ==yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Napp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/scripts.html.slim
doctype html
html
  title Napp
  == stylesheet_link_tag    "admin", :media => "all"
  == javascript_include_tag "application"
  == csrf_meta_tags
body
  .navbar
    .navbar-inner
      .container
        .row
          .span12
            a.brand Scripts
  .container
    ==yield

app/views/layouts/site.html.slim
- content_for :head do
  title Napp
  == stylesheet_link_tag    "application", :media => "all"
  == javascript_include_tag "application"
  == csrf_meta_tags
  style== @site.layout_css
- content_for :content do
  #except-the-app
    ==yield
== Liquid::Template.parse(@site.layout).render('content' => yield(:content), 'head' => yield(:head))

app/views/scripts/index.html.slim
h1 Scripts

- @files.each do |file|

  li
    ==link_to file.titleize, script_path(file)
  

app/views/scripts/show.html.slim
ul.breadcrumb
  li
    ==link_to 'Scripts', scripts_path
    span.divider
      |/
  li.active= @filename
    

h1= @filename

form method="post"
  input type="hidden" name="filename" value=@filename
  button.btn.btn-primary#run-button Run This Code

-if @error
  .alert.alert-error
    =@error

pre
  =@content
  
/ coffee:
  $('#run-button').click ->
    alert('clicked!')

app/views/sites/_form.html.slim
= form_for @site do |f|
  - if @site.errors.any?
    #error_explanation
      h2 = "#{pluralize(@site.errors.count, "error")} prohibited this site from being saved:"
      ul
        - @site.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :subdomain
    = f.text_field :subdomain
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :owner_id
    = f.number_field :owner_id
  .actions = f.submit 'Save'

app/views/sites/edit.html.slim
h1 Editing site

== render 'form'

= link_to 'Show', @site
'|
= link_to 'Back', sites_path

app/views/sites/index.html.slim
h1 Listing sites

table
  tr
    th Subdomain
    th Name
    th Owner
    th
    th
    th

  - @sites.each do |site|
    tr
      td = site.subdomain
      td = site.name
      td = site.owner_id
      td = link_to 'Show', site
      td = link_to 'Edit', edit_site_path(site)
      td = link_to 'Destroy', site, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Site', new_site_path

app/views/sites/new.html.slim
h1 New site

== render 'form'

= link_to 'Back', sites_path

app/views/sites/show.html.slim
p#notice = notice

h1
  = @site.name
  